# cd /d D:\github\SpringCloud\docker-stack-deploy
# docker stack deploy --with-registry-auth -c docker-compose.nginx.yml sc
# for /F %i in ('docker ps -q -f "name=sc_nginx"') do (set CONTAINER_ID=%i)
# docker exec -it %CONTAINER_ID% nginx -t
version: "3"
services:
  nginx:
    image: nginx:1.15.12
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/host_mnt/d/github/SpringCloud/data/Shanghai:/etc/localtime"
      - "/host_mnt/d/github/SpringCloud/data/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/host_mnt/d/github/SpringCloud/data/nginx/conf.d:/etc/nginx/conf.d"
      - "/host_mnt/d/github/SpringCloud/data/nginx/cert:/etc/nginx/cert"
      - "/host_mnt/d/github/SpringCloud/data/nginx/html:/usr/share/nginx/html"
    deploy:
      labels:
        host: dev
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: sc-net