# cd /d D:\github\SpringCloud\docker-stack-deploy
# docker stack deploy --with-registry-auth -c docker-compose.redis.yml sc
# for /F %i in ('docker ps -q -f "name=sc_redis"') do (set CONTAINER_ID=%i)
# docker exec -it %CONTAINER_ID% redis-cli info
version: '3'
services:
  redis:
    image: redis:5.0.6-alpine
    volumes:
      - "/host_mnt/d/github/SpringCloud/data/redis:/data"
    ports:
      - "6379:6379"
    networks:
      - default
    env_file:
      - .env
    deploy:
      labels:
        host: dev
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: sc-net