# docker stack ^
#     deploy ^
#     --with-registry-auth ^
#     -c c:/data/config/local/nginx/docker-compose.yml ^
#     dev
version: "3"
services:
  nginx:
    image: nginx:1.15.12
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/host_mnt/d/github/SpringCloud/data/Shanghai:/etc/localtime"
      - "/host_mnt/d/github/SpringCloud/data/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/host_mnt/d/github/SpringCloud/data/nginx/conf.d:/etc/nginx/conf.d"
      - "/host_mnt/d/github/SpringCloud/data/nginx/cert:/etc/nginx/cert"
      - "/host_mnt/d/github/SpringCloud/data/nginx/html:/usr/share/nginx/html"
    deploy:
      labels:
        host: dev
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: sc-net